doplus_paratronic:
    resource: "@DoplusParatronicBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#FOSUserBundle
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
